-- Zestaw 9
-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2024-05-21 00:15:50 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE clients (
    last_name        VARCHAR2(30),
    delivery_address VARCHAR2(40),
    first_name       VARCHAR2(30),
    client_id        NUMBER(7),
    clients_id       NUMBER NOT NULL
)
LOGGING;

ALTER TABLE clients ADD CONSTRAINT clients_pk PRIMARY KEY ( clients_id );

CREATE TABLE orders (
    num_of_units         NUMBER(4),
    total_cost           NUMBER(4),
    order_status         VARCHAR2(20),
    order_id             NUMBER(7) NOT NULL,
    products_products_id NUMBER NOT NULL,
    clients_clients_id   NUMBER NOT NULL
)
LOGGING;

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( order_id );

CREATE TABLE products (
    product_name VARCHAR2(20),
    type         VARCHAR2(20),
    product_id   NUMBER(7),
    price        NUMBER(4),
    products_id  NUMBER NOT NULL
)
LOGGING;

ALTER TABLE products ADD CONSTRAINT products_pk PRIMARY KEY ( products_id );

ALTER TABLE orders
    ADD CONSTRAINT orders_clients_fk FOREIGN KEY ( clients_clients_id )
        REFERENCES clients ( clients_id )
    NOT DEFERRABLE;

ALTER TABLE orders
    ADD CONSTRAINT orders_products_fk FOREIGN KEY ( products_products_id )
        REFERENCES products ( products_id )
    NOT DEFERRABLE;

CREATE SEQUENCE clients_clients_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER clients_clients_id_trg BEFORE
    INSERT ON clients
    FOR EACH ROW
    WHEN ( new.clients_id IS NULL )
BEGIN
    :new.clients_id := clients_clients_id_seq.nextval;
END;
/

CREATE SEQUENCE products_products_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER products_products_id_trg BEFORE
    INSERT ON products
    FOR EACH ROW
    WHEN ( new.products_id IS NULL )
BEGIN
    :new.products_id := products_products_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          2
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0